server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: UserService
        uri: lb://UserService
        predicates[0]: Path=/api/**
      routes[1]:
        id: AuthorizationService
        uri: lb://AuthorizationService
        predicates[0]: Path=/authorization/**
      routes[2]:
        id: SubscriptionService
        uri: lb://SubscriptionService
        predicates[0]: Path=/subscription/**
      routes[3]:
        id: NotificationService
        uri: lb://NotificationService
        predicates[0]: Path=/api/notification/**
      routes[4]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[5]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
