server:
  port: 0

spring:
  datasource:
    password: F@tiOuss@m@123
    username: postgres
    url: jdbc:postgresql://localhost:5432/userManagementDB
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
